### ISSUE TITLE
Load settings(directory, session, and token etc...) from TOML

### ISSUE THREAD

**Issue by budougumi0617** [budougumi0617/leetgode#7]
Load environment settings from TOML.

```toml

[code]
editor = 'vim'
lang = 'golang'
pick = '${fid}.${slug}'
submission = '${fid}.${slug}.${sid}.${ac}'

[cookies]
csrf = "llfea..."
session = "asdgwea..."

[storage]
cache = 'Problems'
code = '/Users/budougumi0617/go/src/github.com/budougumi0617/leetcode'
root = '~/.leetcode'
scripts = 'scripts'
```
TOML structure is defined by leetcode-cli
https://github.com/clearloop/leetcode-cli#cookies
